name: Build Image
on: 
  push: 
    branches:
      - master
  paths-ignore:
      - README.md
  schedule:
    - cron: 0 8 * * 1

jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: superng6/qbittorrent
              platform: linux/amd64,linux/arm64,linux/arm/v7
              tag: latest
              dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
              dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
